serlimar_serledge_home:
    path:     /
    defaults: { _controller: SerlimarSerlEdgeBundle:Default:index }

serlimar_serledge_payment:
    path:     /payment
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:index }
    
serlimar_serledge_create_payment:
    path:     /payment/create
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:create }

serlimar_serledge_update_payment:
    path:     /payment/{id}/update
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:update }
    methods:  [GET,POST]
  #  condition: "request.isXMLHttpRequest()"

serlimar_serledge_delete_payment:
    path:     /payment/{id}/delete
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:delete }

serlimar_serledge_show_payment:
    path:     /payment/{id}/show
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:show }
    methods:  [GET]
    
serlimar_serledge_receipt_payment:
    path:     /payment/{id}/receipt
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:receipt }

serlimar_serledge_printall_payment:
    path:     /payment/print
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:printAll }
    
serlimar_serledge_payment_clearfilter:
    path:     /clearfilter
    defaults: { _controller: SerlimarSerlEdgeBundle:Payment:clearFilter }
    
serlimar_serledge_customer_proxy_payment:
    path:     /customer/{customerid}
    defaults: { _controller: SerlimarSerlEdgeBundle:Customer:proxyPayment }
    
serlimar_serledge_customer:
    path:     /customer
    defaults: { _controller: SerlimarSerlEdgeBundle:Customer:index }
    
serlimar_serledge_customer_name:
    path:     /customer/{id}/name
    defaults: { _controller: SerlimarSerlEdgeBundle:Customer:name }
    
serlimar_serledge_user:
    path:     /user
    defaults: { _controller: SerlimarSerlEdgeBundle:User:index }
    
serlimar_serledge_show_user:
    path:     /user/{id}/show
    defaults: { _controller: SerlimarSerlEdgeBundle:User:show }
    
serlimar_serledge_create_user:
    path:     /user/create
    defaults: { _controller: SerlimarSerlEdgeBundle:User:create }
    
serlimar_serledge_update_user:
    path:     /user/{id}/update
    defaults: { _controller: SerlimarSerlEdgeBundle:User:update }
    methods:  [GET,POST]
    
serlimar_serledge_delete_user:
    path:     /user/{id}/delete
    defaults: { _controller: SerlimarSerlEdgeBundle:User:delete }
    
serlimar_serledge_role:
    path:     /role
    defaults: { _controller: SerlimarSerlEdgeBundle:Role:index }
    
serlimar_serledge_show_role:
    path:     /role/{id}/show
    defaults: { _controller: SerlimarSerlEdgeBundle:Role:show }
    
serlimar_serledge_create_role:
    path:     /role/create
    defaults: { _controller: SerlimarSerlEdgeBundle:Role:create }
    
serlimar_serledge_update_role:
    path:     /role/{id}/update
    defaults: { _controller: SerlimarSerlEdgeBundle:Role:update }
    
serlimar_serledge_delete_role:
    path:     /role/{id}/delete
    defaults: { _controller: SerlimarSerlEdgeBundle:Role:delete }
    
