services:
#    serlimar_serl_edge.example:
#        class: Serlimar\SerlEdgeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    serlimar_serledge_menu_builder:
            class: Serlimar\SerlEdgeBundle\Menu\MenuBuilder
            arguments: ["@knp_menu.factory", "@security.authorization_checker"]

    serlimar_serledge_main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: serlimar_serledge_menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

            
    serlimar_user_provider:
        class: Serlimar\SerlEdgeBundle\Provider\SerlimarUserProvider
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"

    serlimar_serledge_form_role_collection_roles:
        class: Serlimar\SerlEdgeBundle\Form\RoleCollectionRolesType
        tags:
            - { name: form.type, alias: roleCollectionRoles }
            
    serlimar_serledge_generate_token:
        class: Serlimar\SerlEdgeBundle\Utilities\TokenGenerator