services:
#    serlimar_serl_edge.example:
#        class: Serlimar\SerlEdgeBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    serlimar_serledge_menu_builder:
            class: Serlimar\SerlEdgeBundle\Menu\MenuBuilder
            arguments: ["@knp_menu.factory"]

    serlimar_serledge_main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: serlimar_serledge_menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

