Serlimar\SerlEdgeBundle\Entity\RefPostAdresen:
    type: entity
    table: ref_post_adresen
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        streetNam:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: STREET_NAM
        streetNum:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: STREET_NUM
        streetSuf:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: STREET_SUF
        apartment:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: APARTMENT
        code1:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Code1
        ssmaTimestamp:
            type: blob
            nullable: true
            length: null
            options:
                fixed: false
            column: SSMA_TimeStamp
    lifecycleCallbacks: {  }
