Serlimar\SerlEdgeBundle\Entity\SysNumbers:
    type: entity
    table: sys_numbers
    id:
        numbers:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Numbers
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
