Serlimar\SerlEdgeBundle\Entity\SysTrimester:
    type: entity
    table: sys_trimester
    id:
        trimesterid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: TrimesterID
            generator:
                strategy: IDENTITY
    fields:
        trimester:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Trimester
        trimestermonthorder:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TrimesterMonthOrder
        trimestermonthserial:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TrimesterMonthSerial
        trimestermonth:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: TrimesterMonth
    lifecycleCallbacks: {  }
