Serlimar\SerlEdgeBundle\Entity\Tblbatch:
    type: entity
    table: tblbatch
    indexes:
        $Register:
            columns:
                - RegisterGUID
        $BachNR:
            columns:
                - Batchnr
        $Reference:
            columns:
                - Reference
        $Date:
            columns:
                - Batchdate
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        registerguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: RegisterGUID
        batchnr:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Batchnr
        reference:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Reference
        batchdate:
            type: datetime
            nullable: true
            column: Batchdate
        bod:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: BOD
        eod:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: EOD
        transactions:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: Transactions
        notes:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Notes
        closed:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: Closed
        closesdatetime:
            type: datetime
            nullable: true
            column: ClosesDateTime
        canceled:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: Canceled
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
    lifecycleCallbacks: {  }
