Serlimar\SerlEdgeBundle\Entity\Tblcontainers:
    type: entity
    table: tblcontainers
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        containerid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ContainerID
        container:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: Container
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Description
        companyid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CompanyID
        companyguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: CompanyGUID
        defaultmaterial:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: DefaultMaterial
        defaultmaterialguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: DefaultMaterialGUID
        tareweight:
            type: float
            nullable: true
            precision: 10
            scale: 0
        taredate:
            type: datetime
            nullable: true
        manualentry:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: ManualEntry
        memo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Memo
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
    lifecycleCallbacks: {  }
