Serlimar\SerlEdgeBundle\Entity\Tblcomplaints:
    type: entity
    table: tblcomplaints
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        complaintid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ComplaintID
        complainttypeid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ComplaintTypeID
        complaint:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Complaint
        callbackphone:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: CallbackPhone
        followupdate:
            type: datetime
            nullable: true
            column: FollowUpDate
        followupnote:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: FollowUpNote
        followuptype:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FollowUpType
        note:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Note
        statusid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: StatusID
        statusguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: StatusGUID
        completed:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: Completed
        addressid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: AddressID
        addressguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: AddressGUID
        address:
            type: string
            nullable: true
            length: 75
            options:
                fixed: false
            column: Address
        addressshort:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: AddressShort
        route:
            type: string
            nullable: true
            length: 7
            options:
                fixed: false
            column: Route
        lastchangeuser:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LastChangeUser
        memo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Memo
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
    lifecycleCallbacks: {  }
