Serlimar\SerlEdgeBundle\Entity\Tblcomputerlocations:
    type: entity
    table: tblcomputerlocations
    indexes:
        $LoacationGUID:
            columns:
                - LocationGUID
        $Computer:
            columns:
                - Computername
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        computername:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Computername
        locationguid:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: LocationGUID
        ipaddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: IPAddress
        note:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Note
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
    lifecycleCallbacks: {  }
