Serlimar\SerlEdgeBundle\Entity\Tblproducts:
    type: entity
    table: tblproducts
    indexes:
        $Product:
            columns:
                - Product
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        productsid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ProductsID
        product:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Product
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                default: 'Null'
            column: Description
        unit:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: Unit
        rate:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Rate
        cost:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Cost
        minimumcharge:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: MinimumCharge
        usebracket:
            type: boolean
            nullable: true
            column: UseBracket
        memo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Memo
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: NotActive
    lifecycleCallbacks: {  }
