Serlimar\SerlEdgeBundle\Entity\Tblpaymentdetails:
    type: entity
    table: tblpaymentdetails
    indexes:
        $PaymentGUID:
            columns:
                - PaymentGUID
        $InvoiceGUID:
            columns:
                - InvoiceGUID
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        paymentguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: PaymentGUID
        invoiceguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: InvoiceGUID
        selected:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: Selected
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: Description
        duedate:
            type: datetime
            nullable: true
            column: DueDate
        totalamount:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: TotalAmount
        balance:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Balance
        appliedamount:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: AppliedAmount
        completed:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: Completed
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
    lifecycleCallbacks: {  }
