Serlimar\SerlEdgeBundle\Entity\Tblproductbracket:
    type: entity
    table: tblproductbracket
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        productbracketid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ProductBracketID
        productsid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ProductsID
        productguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: ProductGUID
        cost:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Cost
        weight1:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Weight1
        weight2:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Weight2
        rate:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Rate
        memo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Memo
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
    lifecycleCallbacks: {  }
