Serlimar\SerlEdgeBundle\Entity\Tblreceiptitems:
    type: entity
    table: tblreceiptitems
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        receiptsguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: ReceiptsGUID
        productguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: ProductGUID
        description:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: Description
        qty:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '1'
            column: Qty
        rate:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Rate
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Total
        costs:
            type: float
            nullable: true
            precision: 10
            scale: 0
            options:
                default: '0'
            column: Costs
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        userid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: UserID
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        version:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Version
    lifecycleCallbacks: {  }
