Serlimar\SerlEdgeBundle\Entity\Tblregisters:
    type: entity
    table: tblregisters
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        register:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Register
        changedate:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: ChangeDate
        members:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: Members
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: Description
        memo:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Memo
        notactive:
            type: boolean
            nullable: true
            options:
                default: 'b''0'''
            column: NotActive
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
    lifecycleCallbacks: {  }
