Serlimar\SerlEdgeBundle\Entity\Tbltransactiondetails:
    type: entity
    table: tbltransactiondetails
    indexes:
        $TransactionGUID:
            columns:
                - TransactionGUID
        $Type:
            columns:
                - Type
    id:
        guid:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
            id: true
            column: GUID
            generator:
                strategy: IDENTITY
    fields:
        transactionguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: TransactionGUID
        type:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
            column: Type
        orderid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: OrderID
        itemguid:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: ItemGUID
        description:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: Description
        costs:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Costs
        qty:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Qty
        rate:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Rate
        procent:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Procent
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Total
        tax:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Tax
        reference:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Reference
        reference2:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Reference2
        note:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
            column: Note
        insertuser:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: InsertUser
        timestamp:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: TimeStamp
        useraction:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: UserAction
        useractiondate:
            type: datetime
            nullable: true
            column: UserActionDate
        username:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: UserName
        userid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: UserID
        locked:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Locked
        lockeddate:
            type: datetime
            nullable: true
            column: LockedDate
        lockeduserid:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LockedUserID
        lockedusername:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: LockedUserName
        version:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: Version
    lifecycleCallbacks: {  }
